# Generated by Django 6.0.6 on 2026-07-16 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       ('accounts','0003_alter_course_code')
    ]

    operations = [
    migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
            migrations.CreateModel(
                name='Course',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=100)),
                    ('code', models.CharField(blank=True, max_length=20, null=True)),
                    ('description', models.TextField(blank=True)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'accounts_course',
                    'unique_together': {('name', 'code')},
                },
            ),
            migrations.CreateModel(
                name='Enrolment',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                    ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=20)),
                    ('progress', models.IntegerField(default=0)),
                    ('grade', models.CharField(blank=True, max_length=10)),
                    ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='courses.course')),
                    ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'accounts_enrolment',
                    'unique_together': {('student', 'course')},
                },
            ),
        ],
    ),
]
