# Generated by Django 6.0.6 on 2026-07-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='progress',
        ),
        migrations.AddField(
            model_name='course',
            name='total_submissions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='completed_submissions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
