# Generated by Django 6.0.6 on 2026-07-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject_name', 'code')},
        ),
    ]
