# Generated by Django 6.0.6 on 2026-08-19 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='student_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CompletedEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=150, null=True)),
                ('grade', models.CharField(max_length=1)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_enrolments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
