# Generated by Django 6.0.6 on 2026-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrolment_student_completed_completedenrolment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedenrolment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='completedenrolment',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='student_first_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='student_last_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='student_username',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='teacher_first_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='teacher_last_name',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='teacher_username',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
    ]
