# Generated by Django 6.0.6 on 2026-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_completedenrolment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedenrolment',
            name='course_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='student_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedenrolment',
            name='teacher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
