# Generated by Django 6.0.6 on 2026-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_completedenrolment_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedenrolment',
            name='original_enrolment_id',
            field=models.IntegerField(default='1', unique=True),
            preserve_default=False,
        ),
    ]
