import { useState, useEffect } from "react";
import api from '../../services/api'

function NewEnrolment() {

    const [courseOptions, setCourseOptions] = useState([]);
    const [studentOptions, setStudentOptions] = useState([]);
    //These will capture all available students and all available courses to then populate dropdowns

    const [success, setSuccess] = useState(false) // used for ssuccessful POST, allows message and wipe of page
    const [error, setError] = useState(null)


    const [formData, setFormData] = useState({
        student: "",
        course: ""
    }); // Stores the data generated by the form to be dispayed for debugging and also eventually user verification

    const handleChange = (event) => {

        const { name, value } = event.target;

        setFormData(prev => ({
            ...prev,
            [name]: value
        }));
    };

    const handleSubmit = (event) => {
        event.preventDefault()

        setError(null)

        api.post("/courses/enrolments/create/", formData)
            .then(response => {
                console.log("New enrolment created", response.data);

                setSuccess(true);

                setTimeout(() => {
                    setFormData({
                        student: "",
                        course: ""
                    });

                    setSuccess(false)
                }, 3000)
            })
            .catch(error => {

                console.error("Enrolment creation failure:");

                setError(
                    error.response?.data?.non_field_errors?.[0] ||
                    error.response?.data?.detail ||
                    "Could not create enrolment."
                )

                setTimeout(() => {
                    setError(null)
                }, 2000);
            })
    }

    useEffect(() => {

        const fetchData = async () => {

            try {

                const studentsResponse = await api.get('/accounts/students/');
                const coursesResponse = await api.get('/courses/available/');

                // console.log("Testing")
                // console.log(studentsResponse.data)
                // console.log(coursesResponse.data)

                setStudentOptions(studentsResponse.data)
                setCourseOptions(coursesResponse.data)

                // console.log("TESTING MORE")
                // console.log(studentsResponse.data)
            } catch (error) {
                console.error(error)
            }


        };

        fetchData()

    }, []);

    return (
        <>

            <h1>New Enrolment</h1>
            {success && (
                <p>Enrolment sucessfully created!</p>
            )}

            {error && (
                <p>{error}</p>
            )}

            <form onSubmit={handleSubmit}>
                <label htmlFor="student">Student</label>

                <select
                    id="student"
                    name="student"
                    value={formData.student || ""}
                    onChange={handleChange}
                >
                    <option value="">Select a student:</option>

                    {studentOptions.map(student => {
                        return (
                            <option key={student.id} value={student.id}>
                                {student.username}
                            </option>
                        )
                    })}
                </select>

                <label htmlFor="course">Course</label>

                <select
                    id="course"
                    name="course"
                    value={formData.course || ""}
                    onChange={handleChange}
                >
                    <option value="">Select a course:</option>

                    {courseOptions.map(course => {
                        return (
                            <option key={course.id} value={course.id}>
                                {course.subject_name}
                            </option>
                        )
                    })}
                </select>

                <button type="submit">Submit Enrolment</button>
            </form>
            <pre>
                {JSON.stringify(formData, null, 2)}
            </pre>
        </>
    )


}

export default NewEnrolment